spring:
  application:
    name: api
  datasource:
    #LOCAL
    #url: jdbc:postgresql://localhost:5432/flashcards_app
    #username: postgres
    #password: admin

    #PRODUCTION DB
    #url: jdbc:postgresql://trolley.proxy.rlwy.net:48677/railway?sslmode=require
    #username: postgres
    #password: zBXRuksKShVcYEfbyhlmDmZxUIbOXMGl

    #DEPLOY EM PROD
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        time_zone: America/Sao_Paulo
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 30
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    sql-migration-suffixes: .sql

  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: ${PORT:8080}

app:
  base-url: ${BASE_URL}
  #base-url: http://localhost:8080
  frontend:
    url: ${FRONTEND_URL}
    #url: "http://localhost:5173"

api:
  security:
    token:
      secret: ${JWT_SECRET}
      #secret: ${JWT_SECRET:default-secret-dev}

logging:
  level:
    root: INFO

resend:
  api-key: ${RESEND_API_KEY}
  #api-key: re_NZLL9VQz_J4HdfYYuEV8w9yg7f4GwMbr8
  from: noreplay@updates.fabiotrindade.com.br

cloudinary:
  cloudname: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}
  #cloudname: dckgejjyk
  #api-key: "391144798897956"
  #api-secret: "_TrEGtdv6KkKwdQlleoPtkYH518"

